services:
  app:
    image: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - myNetwork

  db:
    image: postgres:15-alpine
    container_name: game-platform-postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - myNetwork
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_volume:/data
    networks:
      - myNetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - minio-storage:/data
      - minio-config:/root/.minio
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
#      - MINIO_BROWSER_REDIRECT_URL=https://your_domain.com/console/
#      - MINIO_DOMAIN=your_domain.com
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_volume:
  redis_volume:
  minio-storage:
  minio-config:

networks:
  myNetwork:
    driver: bridge
