package error_code

const (
	ERROR                 = "ERROR"
	USER_ALREADY_EXIST    = "USER_ALREADY_EXIST"
	PARSE_ERROR           = "PARSE_ERROR"
	INVALID_PARAMETER     = "INVALID_PARAMETER"
	PASSWORD_DO_NOT_MATCH = "PASSWORD_DO_NOT_MATCH"
	INVALID_LOGIN_DATA    = "INVALID_LOGIN_DATA"
)
