basePath: /
definitions:
  userDTO.ResetPasswordInput:
    properties:
      confirm_password:
        type: string
      password:
        type: string
    required:
    - confirm_password
    - password
    type: object
  userDTO.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  userDTO.SignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    required:
    - email
    - name
    - password
    - password_confirm
    type: object
host: localhost:8080
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: sign in user
      parameters:
      - description: SignInInput
        in: body
        name: SignInInput
        required: true
        schema:
          $ref: '#/definitions/userDTO.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /api/v1/auth/logout:
    get:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: SignUpInput
        in: body
        name: ResetPasswordInput
        required: true
        schema:
          $ref: '#/definitions/userDTO.ResetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "502":
          description: Bad Gateway
swagger: "2.0"
