basePath: /
definitions:
  DTO.AddScoreToSkillInput:
    properties:
      score:
        type: integer
      skill_name:
        type: string
    required:
    - skill_name
    type: object
  DTO.CreateGameInput:
    properties:
      config:
        type: string
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
      skills:
        items:
          $ref: '#/definitions/DTO.CreateSkillInput'
        type: array
      source:
        type: string
    required:
    - description
    - friendly_name
    - name
    - source
    type: object
  DTO.CreateSkillInput:
    properties:
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
    required:
    - description
    - friendly_name
    - name
    type: object
  DTO.ForgotPasswordInput:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  DTO.GameResponse:
    properties:
      config:
        type: string
      created_at:
        type: string
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
      skills:
        items:
          $ref: '#/definitions/DTO.SkillResponseOnly'
        type: array
      source:
        type: string
    type: object
  DTO.GameResponseOnly:
    properties:
      created_at:
        type: string
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
      source:
        type: string
    type: object
  DTO.GamesResponse:
    properties:
      games:
        items:
          $ref: '#/definitions/DTO.GameResponse'
        type: array
    type: object
  DTO.ResetPasswordInput:
    properties:
      password:
        type: string
      password_confirm:
        type: string
    required:
    - password
    - password_confirm
    type: object
  DTO.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  DTO.SignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      password_confirm:
        type: string
    required:
    - email
    - name
    - password
    - password_confirm
    type: object
  DTO.SkillResponse:
    properties:
      description:
        type: string
      friendly_name:
        type: string
      games:
        items:
          $ref: '#/definitions/DTO.GameResponseOnly'
        type: array
      name:
        type: string
    type: object
  DTO.SkillResponseOnly:
    properties:
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
    type: object
  DTO.SkillsResponse:
    properties:
      skills:
        items:
          $ref: '#/definitions/DTO.SkillResponse'
        type: array
    type: object
  DTO.TokenResponse:
    properties:
      access_token:
        type: string
      expired_in:
        type: string
    type: object
  DTO.UpdateGameInput:
    properties:
      config:
        type: string
      description:
        type: string
      friendly_name:
        type: string
      skills:
        items:
          $ref: '#/definitions/DTO.CreateSkillInput'
        type: array
      source:
        type: string
    type: object
  DTO.UpdateUserInput:
    properties:
      age:
        type: integer
      gender:
        type: string
      grade:
        type: integer
    type: object
  DTO.UserResponse:
    properties:
      age:
        type: integer
      continuous_progress:
        type: string
      created_at:
        type: string
      email:
        type: string
      gender:
        type: string
      grade:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
  DTO.UserResponseDTO:
    properties:
      user:
        $ref: '#/definitions/DTO.UserResponse'
    type: object
  DTO.UserSkill:
    properties:
      description:
        type: string
      friendly_name:
        type: string
      name:
        type: string
      score:
        type: integer
    required:
    - description
    - friendly_name
    - name
    type: object
  DTO.UserSkillsResponse:
    properties:
      skills:
        items:
          $ref: '#/definitions/DTO.UserSkill'
        type: array
    type: object
  DTO.UsersResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/DTO.UserResponse'
        type: array
    type: object
  api.Error:
    properties:
      code:
        type: string
      message:
        type: string
      parameter:
        type: string
    type: object
  api.ErrorResponse:
    properties:
      error:
        items:
          $ref: '#/definitions/api.Error'
        type: array
      status:
        type: string
    type: object
  api.Response:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_GamesResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.GamesResponse'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_SkillsResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.SkillsResponse'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_TokenResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.TokenResponse'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_UserResponseDTO:
    properties:
      data:
        $ref: '#/definitions/DTO.UserResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_UserSkillsResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.UserSkillsResponse'
      message:
        type: string
      status:
        type: string
    type: object
  api.SuccessResponse-DTO_UsersResponse:
    properties:
      data:
        $ref: '#/definitions/DTO.UsersResponse'
      message:
        type: string
      status:
        type: string
    type: object
host: https://ocrv-game
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is game platform swagger
  license:
    name: Apache 2.0
    url: h
  termsOfService: http://swagger.io/terms/
  title: GamePlatform API
  version: "1.0"
paths:
  /api/v1/auth/forgot-password:
    post:
      consumes:
      - application/json
      description: forgot password
      parameters:
      - description: ForgotPasswordInput
        in: body
        name: ForgotPasswordInput
        required: true
        schema:
          $ref: '#/definitions/DTO.ForgotPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "401":
          description: User email is not verified
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: sign in user
      parameters:
      - description: SignInInput
        in: body
        name: SignInInput
        required: true
        schema:
          $ref: '#/definitions/DTO.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/logout:
    get:
      consumes:
      - application/json
      description: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: refresh access token
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_TokenResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: sign up user
      parameters:
      - description: SignUpInput
        in: body
        name: SignUpInput
        required: true
        schema:
          $ref: '#/definitions/DTO.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UserResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/reset-password:
    patch:
      consumes:
      - application/json
      description: reset user password
      parameters:
      - description: reset code
        in: path
        name: reset_code
        required: true
        type: string
      - description: ResetPasswordInput
        in: body
        name: ResetPasswordInput
        required: true
        schema:
          $ref: '#/definitions/DTO.ResetPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/auth/verify-email:
    post:
      description: verify user email
      parameters:
      - description: Verification code
        in: path
        name: verify_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Auth
  /api/v1/games/:
    delete:
      description: delete game by id
      parameters:
      - description: Game name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
    get:
      description: get games
      parameters:
      - description: string name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_GamesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
    patch:
      description: update game
      parameters:
      - description: Game name
        in: path
        name: name
        required: true
        type: string
      - description: UpdateGameInput
        in: body
        name: UpdateGameInput
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateGameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
    post:
      consumes:
      - application/json
      description: create game
      parameters:
      - description: CreateGameInput
        in: body
        name: CreateGameInput
        required: true
        schema:
          $ref: '#/definitions/DTO.CreateGameInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Game
  /api/v1/skills/:
    delete:
      description: delete skill by id
      parameters:
      - description: Skill name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Skill
    get:
      description: get skills
      parameters:
      - description: string name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_SkillsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Skill
    post:
      consumes:
      - application/json
      description: create skill
      parameters:
      - description: CreateSkillInput
        in: body
        name: CreateSkillInput
        required: true
        schema:
          $ref: '#/definitions/DTO.CreateSkillInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      tags:
      - Skill
  /api/v1/users/:
    delete:
      description: delete user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - User
    get:
      description: get user by id
      parameters:
      - description: user id
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UsersResponse'
        "500":
          description: Internal Server Error
      tags:
      - User
  /api/v1/users/me:
    get:
      description: get current user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UserResponseDTO'
        "401":
          description: Unauthorized
      tags:
      - User
    patch:
      description: update user
      parameters:
      - description: UpdateUserInput
        in: body
        name: SignInInput
        required: true
        schema:
          $ref: '#/definitions/DTO.UpdateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - User
  /api/v1/users/me/skills:
    get:
      description: get score and the name of the user's skills
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SuccessResponse-DTO_UserSkillsResponse'
        "500":
          description: Internal Server Error
      tags:
      - User
    post:
      description: add score to user skill
      parameters:
      - description: AddScoreToSkillInput
        in: body
        name: AddScoreToSkillInput
        required: true
        schema:
          $ref: '#/definitions/DTO.AddScoreToSkillInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      tags:
      - User
swagger: "2.0"
